### ISSUE TITLE
SX OS Support?

### ISSUE THREAD

**Issue by JigglesTheFett** [Genwald/MiiPort#3]
Hello! 

Just curious if this could run on SX OS or not. When I try to load it I just get a black screen. Doesn't lock up or anything, I can still get back to the home menu, it just throws up a black screen and nothing happens.

Thanks!

**Comment by Genwald** [comment]
I don't know why it wouldn't work on SX OS, but I also have never used SX OS and don't want to go out of my way to support it. TX is a problematic group and SX OS problematic software and last I heard they disbanded after their legal issues. I think it'd be best for you and anyone else currently using SX OS to switch to Atmosphere. It is free and has 95% of the same features since SX OS is a modified version of atmosphere.

**Comment by doctahoo** [comment]
That is sad to read, since there are still many SX OS users out there that could benefit from your tool too. You know, SX OS is a very easy and straightforward system to use, and still can be used with latest games (by lowering the firmware requirement for a game), and doesn't require installing any games (just drop your XCI file on your SD card and go!). For these reasons it is used by many people even today instead of switching to Atmosphère (which will never have XCI mounting support). Most homebrew tools work in SX OS too!

**Comment by Genwald** [comment]
This is not the place to discuss piracy. This sounds like you are jumping through hoops for a slightly different method of transferring your pirated games. SX OS is problematic for many reasons including their illegal use of open source projects. I don't see the need to support an outdated, abandoned, paid, FOSS stealing, closed source, illegal, piracy focused, fork of Atmosphere when any remaining users of it can easily choose to use Atmosphere.
